##################
# STS deployment #
##################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
  namespace: {{ .Values.general.namespace }}
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: "{{ .Values.image_db.repository }}:{{ .Values.image_db.tag }}"
        name: {{ .Values.image_db.repository }} #postgres
        env:
        - name: POSTGRES_USER
          value: {{ .Values.image_db.env_user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.image_db.env_pass }}
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        #emptyDir: {} 
        persistentVolumeClaim:
          claimName: pgsql-pv-claim

##########################
# create a storage class #
##########################
---
kind: StorageClass
apiVersion: storage.k8s.io/v1 #v1
metadata:
  name: pgsql-pv-strgclass
  namespace: {{ .Values.general.namespace }}
provisioner: kubernetes.io/gce-pd #hostpath #microk8s.io/hostpath # needs "microk8s enable storage"
reclaimPolicy: Retain # Retain storage even if we delete PVC
volumeBindingMode: Immediate
parameters:
  type: pd-ssd # ssd

###################################
# create a Persistant Volume (PV) #
###################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv-volume
  namespace: {{ .Values.general.namespace }}
  labels:
    type: local
spec:
  storageClassName: pgsql-pv-strgclass
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: {{ .Values.image_db.pdName }}
    fsType: ext4

##########################################
# create a Persistant Volume Claim (PVC) #
##########################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pv-claim
  namespace: {{ .Values.general.namespace }}
spec:
  storageClassName: pgsql-pv-strgclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


# helpfull resources:
# https://stackoverflow.com/questions/58615019/how-to-change-a-kubernetes-hostpath-provisioner-mount-path