##################
# STS deployment #
##################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: db
  name: db
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  serviceName: db
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: {{ .Values.image_db.repository }}':'{{ .Values.image_db.tag }}
        name: {{ .Values.image_db.repository }} #postgres
        env:
        - name: POSTGRES_USER
          value: {{ .Values.image_db.env_user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.image_db.env_pass }}
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        #emptyDir: {} 
        persistentVolumeClaim:
          claimName: pgsql-pv-claim

##########################
# create a storage class #
##########################
---
kind: StorageClass
apiVersion: v1 #storage.k8s.io/v1
metadata:
  name: pgsql-pv-strgclass
  namespace: {{ .Values.global.namespace }}
provisioner: hostpath #microk8s.io/hostpath # needs "microk8s enable storage"
volumeBindingMode: Immediate

###################################
# create a Persistant Volume (PV) #
###################################
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgsql-pv-volume
  namespace: {{ .Values.global.namespace }}
  labels:
    type: local
spec:
  storageClassName: pgsql-pv-strgclass
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #pre-created folder on the following path + took ownership
    path: {{ .Values.image_db.storage_path }} #"/mnt/k8s-pv-data"

##########################################
# create a Persistant Volume Claim (PVC) #
##########################################
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-pv-claim
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: pgsql-pv-strgclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


# helpfull resources:
# https://stackoverflow.com/questions/58615019/how-to-change-a-kubernetes-hostpath-provisioner-mount-path