apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: vote
spec:
  replicas: {{ .Values.image_redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: "{{ .Values.image_redis.repository }}" #redis:alpine
        imagePullPolicy: {{ .Values.image_redis.pullPolicy }}
        name: redis
        ports:
        - containerPort: {{ .Values.image_redis.port }}
          name: redis
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {} 
