apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: "redis-service"
    port: {{ .Values.image_redis.port }}
    targetPort: {{ .Values.image_redis.targetPort }}
  selector:
    app: redis
  
