apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{- include "my-vote.labels" . | nindent 4 }} #vote
  name: {{ include "my-vote.fullname" . }} #vote
  namespace: {{ include "my-vote.namespace" }}  #vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{- include "my-vote.selectorLabels" . | nindent 6 }} #vote
  template:
    metadata:
      labels:
        app: {{- include "my-vote.selectorLabels" . | nindent 8 }} #vote
    spec:
      containers:
      - image: {{ .Values.image_vote.repository }}':' {{ .Values.image_vote.tag}} #{{ .Chart.AppVersion }} #itay47/voting-app:Worker_core31
        name: {{ .Chart.Name }} #vote
        ports:
        - containerPort: 80
          name: {{ .Values.GLOBAL.namespace}}
