apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.GLOBAL.namespace}}
  name: {{ .Values.GLOBAL.namespace}}
  namespace: {{ .Values.GLOBAL.namespace}}
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: {{ .Values.image_vote.port}}
    targetPort: {{ .Values.image_vote.targetPort}}
    nodePort: {{ .Values.image_vote.nodePort}}
  selector:
    app: {{ .Values.GLOBAL.namespace}}
  
