apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.general.namespace }}
  name: {{ .Values.general.namespace }}
  namespace: {{ .Values.general.namespace }}
spec:
  type: NodePort
  ports:
  - name: "vote-service"
    port: {{ .Values.image_vote.port }}
    targetPort: {{ .Values.image_vote.targetPort }}
    nodePort: {{ .Values.image_vote.nodePort }}
  selector:
    app: {{ .Values.general.namespace }}
  
