apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.general.namespace }} #vote
  name: {{ .Values.general.namespace }} #vote
  namespace: {{ .Values.general.namespace }}  #vote
spec:
  replicas: {{ .Values.image_vote.replicas }}
  selector:
    matchLabels:
      app: {{.Values.general.namespace }} #vote
  template:
    metadata:
      labels:
        app: {{.Values.general.namespace }} #vote
    spec:
      containers:
      - image: "{{ .Values.image_vote.repository }}:{{ .Values.image_vote.tag }}" #{{ .Chart.AppVersion }} #itay47/voting-app:Worker_core31
        imagePullPolicy: {{ .Values.image_vote.pullPolicy }}
        name: {{ .Chart.Name }} #vote
        ports:
        - containerPort: {{ .Values.image_vote.targetPort }}
          name: {{ .Values.general.namespace }}
