apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
  namespace: {{ .Values.GLOBAL.namespace }}
spec:
  replicas: {{ .Values.image_worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ .Values.image_worker.repository }}':'{{ .Values.image_worker.tag }}  #dockersamples/examplevotingapp_worker
        name: worker
