general:
  namespace: vote
  appVersion: 21.06.21.1433
image_vote:
  repository: itay47/voting-app
  pullPolicy: "IfNotPresent"
  port: 5000
  targetPort: 80
  nodePort: 31000
  replicas: 1
  tag: "vote_v0.111"
image_result:
  repository: itay47/voting-app
  pullPolicy: "IfNotPresent"
  port: 5001
  targetPort: 80
  nodePort: 31001
  replicas: 1
  tag: "result_16.6.21"
image_worker:
  repository: itay47/voting-app
  pullPolicy: "IfNotPresent"
  replicas: 1
  tag: "worker_v0.1.222"
image_redis:
  replicas: 1
  repository: redis:alpine
  pullPolicy: "IfNotPresent"
  port: 6379
  targetPort: 6379
image_db:
  repository: postgres
  pullPolicy: "IfNotPresent"
  tag: "9.4"
  env_user: postgres
  env_pass: postgres
  storage_path: /mnt/disks/ssd0
